name: Deploy Containers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update deployment directory
        run: |
          rsync -av --delete \
            --exclude '.env' \
            --exclude '.git' \
            ./ /home/harry/homeserver-deployments/
            
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u HarryIsCodingg --password-stdin
          
      - name: Pull new images
        run: |
          cd /home/harry/homeserver-deployments
          docker compose pull

      - name: Restart containers
        run: |
          cd /home/harry/homeserver-deployments
          docker compose up -d --remove-orphans
